create table if not exists public.vie_groupe_options (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  module_key text not null,
  nom text not null,
  validite_type text not null default 'aucune',
  validite_date date,
  validite_delai_nombre int,
  validite_delai_unite text,
  created_by text,
  updated_by text
);

alter table public.vie_groupe_options enable row level security;

drop policy if exists "vie_groupe_options_select_authenticated" on public.vie_groupe_options;
create policy "vie_groupe_options_select_authenticated"
on public.vie_groupe_options
for select
to authenticated
using (true);

drop policy if exists "vie_groupe_options_insert_authenticated" on public.vie_groupe_options;
create policy "vie_groupe_options_insert_authenticated"
on public.vie_groupe_options
for insert
to authenticated
with check (true);

drop policy if exists "vie_groupe_options_update_authenticated" on public.vie_groupe_options;
create policy "vie_groupe_options_update_authenticated"
on public.vie_groupe_options
for update
to authenticated
using (true)
with check (true);

drop policy if exists "vie_groupe_options_delete_authenticated" on public.vie_groupe_options;
create policy "vie_groupe_options_delete_authenticated"
on public.vie_groupe_options
for delete
to authenticated
using (true);

create table if not exists public.caisse_cafe_rappels (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  collegue text not null unique,
  actif boolean not null default true,
  message text not null default 'oublie pas de payer vielle pince',
  created_by text,
  updated_by text
);

alter table public.caisse_cafe_rappels enable row level security;

drop policy if exists "caisse_cafe_rappels_select_authenticated" on public.caisse_cafe_rappels;
create policy "caisse_cafe_rappels_select_authenticated"
on public.caisse_cafe_rappels
for select
to authenticated
using (true);

drop policy if exists "caisse_cafe_rappels_insert_authenticated" on public.caisse_cafe_rappels;
create policy "caisse_cafe_rappels_insert_authenticated"
on public.caisse_cafe_rappels
for insert
to authenticated
with check (true);

drop policy if exists "caisse_cafe_rappels_update_authenticated" on public.caisse_cafe_rappels;
create policy "caisse_cafe_rappels_update_authenticated"
on public.caisse_cafe_rappels
for update
to authenticated
using (true)
with check (true);

drop policy if exists "caisse_cafe_rappels_delete_authenticated" on public.caisse_cafe_rappels;
create policy "caisse_cafe_rappels_delete_authenticated"
on public.caisse_cafe_rappels
for delete
to authenticated
using (true);
