create table if not exists public.vie_groupe_dossiers (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  type text not null,
  collegue text not null,
  data jsonb not null default '{}'::jsonb,
  created_by text,
  updated_by text
);

alter table public.vie_groupe_dossiers enable row level security;

drop policy if exists "vie_groupe_dossiers_select_authenticated" on public.vie_groupe_dossiers;
create policy "vie_groupe_dossiers_select_authenticated"
on public.vie_groupe_dossiers
for select
to authenticated
using (true);

drop policy if exists "vie_groupe_dossiers_insert_authenticated" on public.vie_groupe_dossiers;
create policy "vie_groupe_dossiers_insert_authenticated"
on public.vie_groupe_dossiers
for insert
to authenticated
with check (true);

drop policy if exists "vie_groupe_dossiers_update_own_or_admin" on public.vie_groupe_dossiers;
create policy "vie_groupe_dossiers_update_own_or_admin"
on public.vie_groupe_dossiers
for update
to authenticated
using (
  created_by in (
    select u.username
    from public.users u
    where lower(coalesce(u.auth_email, '')) = lower(auth.jwt() ->> 'email')
      or (
        u.username = 'tolier'
        and lower(auth.jwt() ->> 'email') = 'tayeb.berkouk.tbt@gmail.com'
      )
  )
  or exists (
    select 1
    from public.users u
    where u.role in ('LE TÔLIER', 'ADMINISTRATEUR')
      and (
        lower(coalesce(u.auth_email, '')) = lower(auth.jwt() ->> 'email')
        or (
          u.username = 'tolier'
          and lower(auth.jwt() ->> 'email') = 'tayeb.berkouk.tbt@gmail.com'
        )
      )
  )
)
with check (true);

drop policy if exists "vie_groupe_dossiers_delete_admin" on public.vie_groupe_dossiers;
create policy "vie_groupe_dossiers_delete_admin"
on public.vie_groupe_dossiers
for delete
to authenticated
using (
  exists (
    select 1
    from public.users u
    where u.role in ('LE TÔLIER', 'ADMINISTRATEUR')
      and (
        lower(coalesce(u.auth_email, '')) = lower(auth.jwt() ->> 'email')
        or (
          u.username = 'tolier'
          and lower(auth.jwt() ->> 'email') = 'tayeb.berkouk.tbt@gmail.com'
        )
      )
  )
);
