create table if not exists public.numeros_utiles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  grade text,
  nom text,
  prenom text,
  fonction text,
  numero text,
  numeros jsonb not null default '[]'::jsonb,
  observations text,
  created_by text,
  updated_by text
);

alter table public.numeros_utiles enable row level security;

drop policy if exists "numeros_utiles_select_authenticated" on public.numeros_utiles;
create policy "numeros_utiles_select_authenticated"
on public.numeros_utiles
for select
to authenticated
using (true);

drop policy if exists "numeros_utiles_insert_authenticated" on public.numeros_utiles;
create policy "numeros_utiles_insert_authenticated"
on public.numeros_utiles
for insert
to authenticated
with check (true);

drop policy if exists "numeros_utiles_update_authenticated" on public.numeros_utiles;
create policy "numeros_utiles_update_authenticated"
on public.numeros_utiles
for update
to authenticated
using (true)
with check (true);

drop policy if exists "numeros_utiles_delete_authenticated" on public.numeros_utiles;
create policy "numeros_utiles_delete_admin"
on public.numeros_utiles
for delete
to authenticated
using (
  exists (
    select 1
    from public.users u
    where u.role in ('LE TÔLIER', 'ADMINISTRATEUR')
      and (
        lower(coalesce(u.auth_email, '')) = lower(auth.jwt() ->> 'email')
        or (
          u.username = 'tolier'
          and lower(auth.jwt() ->> 'email') = 'tayeb.berkouk.tbt@gmail.com'
        )
      )
  )
);
