create table if not exists public.camps (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  categorie text not null,
  lieu text,
  adresse text,
  famille text,
  identite_id bigint,
  vehicule text,
  faits text,
  observations text,
  created_by text,
  updated_by text
);

alter table public.camps enable row level security;

drop policy if exists "camps_select_authenticated" on public.camps;
create policy "camps_select_authenticated"
on public.camps
for select
to authenticated
using (true);

drop policy if exists "camps_insert_authenticated" on public.camps;
create policy "camps_insert_authenticated"
on public.camps
for insert
to authenticated
with check (true);

drop policy if exists "camps_update_authenticated" on public.camps;
create policy "camps_update_authenticated"
on public.camps
for update
to authenticated
using (true)
with check (true);

drop policy if exists "camps_delete_admin" on public.camps;
create policy "camps_delete_admin"
on public.camps
for delete
to authenticated
using (
  exists (
    select 1
    from public.users u
    where u.role in ('LE TÔLIER', 'ADMINISTRATEUR')
      and (
        lower(coalesce(u.auth_email, '')) = lower(auth.jwt() ->> 'email')
        or (
          u.username = 'tolier'
          and lower(auth.jwt() ->> 'email') = 'tayeb.berkouk.tbt@gmail.com'
        )
      )
  )
);
