create table if not exists public.p4_conges (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  collegue text not null,
  date_debut date not null,
  date_fin date not null,
  type text not null,
  statut text not null default 'demande',
  commentaire text,
  created_by text,
  updated_by text
);

alter table public.p4_conges enable row level security;

drop policy if exists "p4_conges_select_authenticated" on public.p4_conges;
create policy "p4_conges_select_authenticated"
on public.p4_conges
for select
to authenticated
using (true);

drop policy if exists "p4_conges_insert_authenticated" on public.p4_conges;
create policy "p4_conges_insert_authenticated"
on public.p4_conges
for insert
to authenticated
with check (true);

drop policy if exists "p4_conges_update_authenticated" on public.p4_conges;
drop policy if exists "p4_conges_update_admin" on public.p4_conges;
create policy "p4_conges_update_admin"
on public.p4_conges
for update
to authenticated
using (
  exists (
    select 1
    from public.users u
    where u.role in ('LE TÔLIER', 'ADMINISTRATEUR')
      and (
        lower(coalesce(u.auth_email, '')) = lower(auth.jwt() ->> 'email')
        or (
          u.username = 'tolier'
          and lower(auth.jwt() ->> 'email') = 'tayeb.berkouk.tbt@gmail.com'
        )
      )
  )
)
with check (
  exists (
    select 1
    from public.users u
    where u.role in ('LE TÔLIER', 'ADMINISTRATEUR')
      and (
        lower(coalesce(u.auth_email, '')) = lower(auth.jwt() ->> 'email')
        or (
          u.username = 'tolier'
          and lower(auth.jwt() ->> 'email') = 'tayeb.berkouk.tbt@gmail.com'
        )
      )
  )
);

drop policy if exists "p4_conges_delete_authenticated" on public.p4_conges;
drop policy if exists "p4_conges_delete_admin" on public.p4_conges;
create policy "p4_conges_delete_admin"
on public.p4_conges
for delete
to authenticated
using (
  exists (
    select 1
    from public.users u
    where u.role in ('LE TÔLIER', 'ADMINISTRATEUR')
      and (
        lower(coalesce(u.auth_email, '')) = lower(auth.jwt() ->> 'email')
        or (
          u.username = 'tolier'
          and lower(auth.jwt() ->> 'email') = 'tayeb.berkouk.tbt@gmail.com'
        )
      )
  )
);
